apiVersion: apps/v1
kind: Deployment
metadata:
  name: legollyweb
  namespace: legolly
spec:
  replicas: 2             
  selector:
    matchLabels:
      app: legollyweb
  template:
    metadata:
      labels:
        app: legollyweb
    spec:
      containers:
      - image: ajpahl1008/legollyweb-x86
        name: legollyweb-x86
        ports:
        - containerPort: 3000
          name: legollyweb-x86
